-- Intentionally empty. Originally set StaffingAssignment.status default to
-- 'Proposed', but StaffingAssignment was dropped when the v0 schema was
-- rolled back. File preserved (not deleted) to keep migration-check.yml's
-- "no deleted migrations" guarantee.
