-- Add QuestionType enum and column to EducationApplicationQuestion and EducationApplicationTemplateQuestion
-- Run `npx prisma migrate dev` to apply this migration against a live database.
-- This file is a placeholder; the actual SQL will be generated by Prisma.

CREATE TYPE "QuestionType" AS ENUM ('Text', 'Url', 'File');

ALTER TABLE "EducationApplicationQuestion" ADD COLUMN "type" "QuestionType" NOT NULL DEFAULT 'Text';

ALTER TABLE "EducationApplicationTemplateQuestion" ADD COLUMN "type" "QuestionType" NOT NULL DEFAULT 'Text';
