// DocEditor implementation — CLIENT-ONLY (loaded via React.lazy behind the
// mounted gate in DocEditor.tsx; never import this module from a route).
//
// Two modes off one shared view:
//   local  — useCreateBlockNote with schema + normalized initialContent.
//   collab — refcounted Y.Doc cache + HocuspocusProvider + y-indexeddb, bound
//            to the "blocknote" fragment via withCollaboration (the 0.52 API;
//            the old `collaboration` editor option is gone), plus the yUndo
//            keep-alive fix below.

import "@blocknote/shadcn/style.css";
// NOTE: the shadcn Tailwind utilities are generated by the MAIN app.css pass
// (see the @source there). Do not re-emit them from this lazy chunk — a second
// utilities layer loaded after app.css breaks the shell's responsive variants.
import "./theme.css";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from "react";
import * as Y from "yjs";
import {
  relativePositionToAbsolutePosition,
  ySyncPluginKey,
} from "y-prosemirror";
import { createPortal } from "react-dom";
import type { ReactNode } from "react";
import type { EditorState } from "prosemirror-state";
import { withCollaboration } from "@blocknote/core/yjs";
import { en } from "@blocknote/core/locales";
import { CommentsExtension } from "@blocknote/core/comments";
import type { User } from "@blocknote/core";
import {
  SuggestionMenuController,
  useCreateBlockNote,
  FloatingComposerController,
  FloatingThreadController,
  FormattingToolbar,
  FormattingToolbarController,
  BlockTypeSelect,
  BasicTextStyleButton,
  ColorStyleButton,
  CreateLinkButton,
  ThreadsSidebar,
} from "@blocknote/react";
import { DocCommentsRail } from "./comments/DocCommentsRail";
import { BlockNoteView } from "@blocknote/shadcn";

import { countWords, extractHeadings, normalizeInitialContent } from "./blocks-util";
import { acquireCollabDoc, nameToHexColor, releaseCollabDoc, type CollabDocEntry } from "./collab-doc";
import { DaliThreadStore, getOrCreateStore, resolveDocUsers } from "./comments/DaliThreadStore";
import { DocEditorFallback } from "./DocEditor";
import { resolveFeatures, type Features } from "./features";
import { buildSchema, type DocEditorInstance, type DocPartialBlock } from "./schema/build";
import { BLOCKNOTE_FRAGMENT } from "./schema/configs";
import { getMentionMenuItems } from "./schema/mention";
import { getFilteredDocSlashMenuItems } from "./schema/slash-menu";
import { DEFAULT_SIGNING_CTX, SigningContext } from "./signing-context";
import { usePresence, useRegisterCollabEditor } from "../collab/PresenceProvider";
import type { DocCollabConfig, DocCommentsConfig, DocEditorProps } from "./types";
import { uploadEditorImage } from "./upload";

export default function DocEditorImpl(props: DocEditorProps) {
  const features = resolveFeatures(props.features);
  if (props.collab) {
    return <CollabDoc {...props} features={features} collab={props.collab} />;
  }
  return <LocalDoc {...props} features={features} />;
}

// Resolved-features variants of the props (presets already applied).
type ResolvedProps = Omit<DocEditorProps, "features"> & { features: Features };

// ─── Local (non-collab) mode ────────────────────────────────────────────────

function LocalDoc(props: ResolvedProps) {
  const schema = useDocSchema(props.features);
  const dictionary = useDocDictionary(props.placeholder);
  // Normalized once per (schema, content) pair; the editor is recreated on
  // schema/dictionary change anyway, so this rides the same memo.
  const initialContent = useMemo(
    () => normalizeInitialContent<DocPartialBlock>(props.initialContent),
    [props.initialContent],
  );

  const editor = useCreateBlockNote(
    {
      schema,
      initialContent,
      dictionary,
      uploadFile: props.features.images ? uploadEditorImage : undefined,
    },
    [schema, dictionary],
  );

  return <DocView {...props} editor={editor} />;
}

// ─── Collaborative mode ─────────────────────────────────────────────────────

function CollabDoc(props: ResolvedProps & { collab: DocCollabConfig }) {
  const { documentName, token } = props.collab;
  const [entry, setEntry] = useState<CollabDocEntry | null>(null);

  useEffect(() => {
    const acquired = acquireCollabDoc(documentName, token);
    setEntry(acquired);
    return () => {
      releaseCollabDoc(documentName);
      setEntry(null);
    };
  }, [documentName, token]);

  // Gate the inner component (and key it per room) so useCreateBlockNote runs
  // once with the final fragment/provider.
  if (!entry) return <DocEditorFallback className={props.className} />;
  return <CollabDocInner key={documentName} {...props} entry={entry} />;
}

function CollabDocInner(
  props: ResolvedProps & { collab: DocCollabConfig; entry: CollabDocEntry },
) {
  const { entry } = props;
  const { userName, userId } = props.collab;
  const schema = useDocSchema(props.features);
  const dictionary = useDocDictionary(props.placeholder);
  const threadStore = useThreadStore(props.comments);

  const editor = useCreateBlockNote(
    // withCollaboration injects the CollaborationExtension (ySync + yCursor +
    // yUndo + schemaMigration), disables prosemirror-history (yUndo is
    // authoritative) and pins initialContent to a fixed block id so two fresh
    // clients don't seed conflicting random initial blocks.
    withCollaboration({
      schema,
      dictionary,
      uploadFile: props.features.images ? uploadEditorImage : undefined,
      // Wire CommentsExtension when a threadStore is available. Extensions are
      // passed through withCollaboration unchanged (see dist/yjs.js).
      ...(threadStore
        ? {
            extensions: [
              CommentsExtension({
                threadStore,
                resolveUsers: makeResolveDocUsers(threadStore),
              }),
            ],
          }
        : {}),
      collaboration: {
        fragment: entry.ydoc.getXmlFragment(BLOCKNOTE_FRAGMENT),
        // Awareness color must be 6-digit hex (y-prosemirror appends a hex
        // alpha suffix); extra keys like userId ride along for presence.
        user: {
          name: userName,
          color: nameToHexColor(userName),
          ...(userId ? { userId } : {}),
        },
        // HocuspocusProvider.awareness is `Awareness | null`; option wants
        // `Awareness | undefined`.
        provider: { awareness: entry.provider.awareness ?? undefined },
        // "always" is broken upstream (label CSS keys off a data-active
        // attribute that mode never sets); "activity" shows labels on cursor
        // movement/typing.
        showCursorLabels: "activity",
      },
    }),
    // threadStore is stable per (pageId, userId) via useThreadStore; adding it
    // here is safe and ensures the editor is re-created if comments config
    // changes (e.g. canEdit toggle).
    [schema, dictionary, entry, threadStore],
  );

  // FIX (undo no-ops in collab): y-prosemirror's yUndoPlugin creates its
  // UndoManager in plugin-STATE init but destroys it from the plugin VIEW's
  // destroy(). BlockNote 0.52 / tiptap v3 keep the EditorState — plugin state
  // included — across editor.unmount()/mount() (StrictMode's simulated
  // remount, BlockNoteView's editable-change remount), so the first unmount
  // kills the manager and every later mount reuses the dead instance: undo
  // permanently no-ops. Neuter destroy() so the manager's lifetime matches the
  // EditorState that owns it; its real end of life is releaseCollabDoc's
  // ydoc.destroy(). Found by duck-typing over the live plugin list rather than
  // yUndoPluginKey.getState() — the prod bundle can inline y-prosemirror's key
  // module twice, making key-based lookup silently return null (the same trap
  // the legacy CollaborativeEditor documents).
  useEffect(() => {
    const um = findCollabUndoManager(editor.prosemirrorState);
    if (um) um.destroy = () => {};
  }, [editor]);

  return <DocView {...props} editor={editor} collabEntry={entry} />;
}

function findCollabUndoManager(state: EditorState): Y.UndoManager | null {
  for (const plugin of state.plugins) {
    const pluginState = plugin.getState(state) as { undoManager?: Y.UndoManager } | undefined;
    if (pluginState && typeof pluginState.undoManager?.undo === "function") {
      return pluginState.undoManager;
    }
  }
  return null;
}

// ─── Comments helpers ────────────────────────────────────────────────────────

/**
 * Returns the shared DaliThreadStore for (pageId, currentUserId, canComment,
 * canResolve) — or null when comments config is absent. Uses the module-level
 * registry so the editor, the count hook, and the panel all read/write the
 * same in-memory thread map; mutations update the bubble count immediately
 * without waiting for the next poll cycle.
 */
function useThreadStore(comments: DocCommentsConfig | undefined): DaliThreadStore | null {
  return useMemo(() => {
    if (!comments) return null;
    return getOrCreateStore(comments.pageId, {
      currentUserId: comments.currentUserId,
      canComment: comments.canComment,
      canResolve: comments.canResolve,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comments?.pageId, comments?.currentUserId, comments?.canComment, comments?.canResolve]);
}

/**
 * Returns a resolveUsers callback for CommentsExtension. BlockNote calls it
 * with `(userIds, store)` and expects `Promise<User[]>`.
 *
 * We use W3's /api/users/resolve endpoint (with a metadata-seed shortcut so
 * known users don't need an extra round-trip).
 */
function makeResolveDocUsers(store: DaliThreadStore) {
  return async (userIds: string[]): Promise<User[]> => {
    const resolved = await resolveDocUsers(userIds, store);
    return resolved as User[];
  };
}

// ─── Shared view + chrome ───────────────────────────────────────────────────

function DocView(
  props: ResolvedProps & { editor: DocEditorInstance; collabEntry?: CollabDocEntry },
) {
  const { editor, features, collabEntry } = props;
  useDocChrome(editor, props);
  const isDark = useIsDark();

  // Hand hosts the live instance (ref-routed so a new callback identity per
  // render doesn't re-fire the effect).
  const onReadyRef = useRef(props.onEditorReady);
  onReadyRef.current = props.onEditorReady;
  useEffect(() => {
    onReadyRef.current?.(editor);
  }, [editor]);

  // ── Jump-to-cursor (Feature B4-1) ─────────────────────────────────────────
  // One-shot scroll to a remote peer's current cursor position when their
  // avatar is clicked in the PresenceBar. NOT continuous follow (Notion parity).
  //
  // Implementation: the collab doc awareness (yCursorPlugin) stores
  // `cursor: { anchor, head }` as Yjs relative positions, keyed by collab-doc
  // clientId. The PresenceProvider's `followPeer` passes the SIDECAR presence-
  // room clientId, which is a different Y.Doc and a different clientId. We
  // bridge via `user.userId`, which both rooms carry on awareness state.
  // Finding the collab-doc entry for the peer: scan collab-doc awareness for
  // the entry whose `user.userId` matches the sidecar peer's userId.
  const editorRef = useRef(editor);
  editorRef.current = editor;

  // Sidecar peers list — used to bridge sidecar clientId → userId.
  const presence = usePresence();
  const presenceRef = useRef(presence);
  presenceRef.current = presence;

  const followPeer = useCallback(
    (sidecarClientId: number) => {
      const collabAwareness = collabEntry?.provider.awareness;
      if (!collabAwareness) return;

      // Resolve the sidecar clientId → userId via the sidecar peers list.
      const sidecarPeer = presenceRef.current?.peers.find(
        (p) => p.clientId === sidecarClientId,
      );
      const targetUserId = sidecarPeer?.userId;
      if (!targetUserId) return;

      // Find the collab-doc awareness entry for this userId.
      let cursor: { anchor: unknown; head: unknown } | null = null;
      for (const [, state] of collabAwareness.getStates()) {
        const u = state.user as { userId?: string } | undefined;
        if (u?.userId === targetUserId && state.cursor) {
          cursor = state.cursor as { anchor: unknown; head: unknown };
          break;
        }
      }
      // Graceful no-op: peer hasn't placed their cursor in this editor yet.
      if (!cursor) return;

      try {
        const ed = editorRef.current;
        const pmView = ed.prosemirrorView;
        // ySyncPluginKey.getState() is untyped in the d.ts — cast to the known
        // runtime shape (verified in y-prosemirror/src/plugins/sync-plugin.js).
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const syncState = ySyncPluginKey.getState(pmView.state) as any;
        if (!syncState?.doc || !syncState?.type || !syncState?.binding) return;

        const absPos = relativePositionToAbsolutePosition(
          syncState.doc as Y.Doc,
          syncState.type as Y.XmlFragment,
          Y.createRelativePositionFromJSON(cursor.head),
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          syncState.binding.mapping as any,
        );
        if (absPos === null) return;

        const clamped = Math.max(
          0,
          Math.min(absPos, pmView.state.doc.content.size - 1),
        );
        const { node } = pmView.domAtPos(clamped);
        const el = node instanceof Element ? node : node.parentElement;
        el?.scrollIntoView({ behavior: "smooth", block: "center" });

        // Flash the cursor caret element so the user can spot the exact
        // location. The collab caret is inside a .bn-collaboration-cursor__base
        // span inserted by BlockNote's yCursorPlugin.
        const caret = el?.closest<HTMLElement>(".bn-collaboration-cursor__base");
        if (caret) {
          caret.classList.add("dali-cursor-flash");
          setTimeout(() => caret.classList.remove("dali-cursor-flash"), 1500);
        }
      } catch {
        // Defensive: position resolution can fail if the collab doc hasn't
        // fully synced. Graceful no-op — next click will work.
      }
    },
    [collabEntry],
  );

  // scrollIntoView for the editor container: called by PresenceProvider before
  // followPeer so the editor is in view before we scroll to the cursor.
  const viewRef = useRef<HTMLDivElement | null>(null);
  const scrollIntoView = useCallback(() => {
    viewRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, []);

  const editorId = props.collab?.documentName ?? "local";

  // reportFocus tells PresenceProvider which editor is active, enabling the
  // PresenceBar's "Jump to cursor" button for this editor's peers.
  const { reportFocus } = useRegisterCollabEditor({ editorId, followPeer, scrollIntoView });

  // Notify PresenceProvider when the editor gains focus so the avatar chip
  // becomes followable while this editor is the active one.
  const reportFocusRef = useRef(reportFocus);
  reportFocusRef.current = reportFocus;
  useEffect(() => {
    const pmView = editor.prosemirrorView;
    if (!pmView) return;
    const dom = pmView.dom as HTMLElement;
    const onFocus = () => reportFocusRef.current();
    dom.addEventListener("focus", onFocus, true);
    return () => dom.removeEventListener("focus", onFocus, true);
  }, [editor]);

  const hasComments = Boolean(props.comments);
  const panelOpen = props.comments?.panelOpen ?? false;
  const panelTargetId = props.comments?.panelTargetId;
  const railVisible = props.comments?.railVisible ?? false;
  const railTargetId = props.comments?.railTargetId;
  const editorContentRef = props.comments?.editorContentRef;

  // The floating comment composer and thread popover portal into a div that
  // lives INSIDE the .dali-doc wrapper. This is the La Suite / BlockNote 0.52
  // fix for the "composer can't receive input" bug:
  //
  // Root cause: when portalElement is undefined, FloatingPortal (used internally
  // by GenericPopover) falls back to document.body. Floating UI's useDismiss
  // then watches for mousedown events outside the floating element — but the
  // editor's .bn-editor div is also "outside" document.body's subtree from
  // useDismiss's perspective (it's a sibling, not an ancestor). So a mousedown
  // on the composer triggers dismiss before the click lands.
  //
  // Fix: pass a portalElement that is INSIDE the .dali-doc subtree. BlockNoteView
  // accepts `portalElements={{ comments: element }}` and passes it through to
  // both FloatingComposerController and FloatingThreadController. The floating
  // container is now a sibling of the editor content (inside .dali-doc), so
  // useDismiss's reference tracking sees clicks in the composer as "inside".
  //
  // We use a ref-attached div rendered as a sibling of <BlockNoteView> inside
  // .dali-doc; the ref is stable across renders.
  const floatingRootRef = useRef<HTMLDivElement | null>(null);

  // Portal target for ThreadsSidebar: when the panel is open, we want
  // <ThreadsSidebar> to render inside the panel's #panelTargetId div.
  // We must stay inside a BlockNoteView context, so DocEditorImpl creates the
  // portal here (inside the editor's React tree) rather than from the panel.
  const [panelTarget, setPanelTarget] = useState<Element | null>(null);
  useEffect(() => {
    if (panelOpen && panelTargetId) {
      const el = document.getElementById(panelTargetId);
      setPanelTarget(el);
    } else {
      setPanelTarget(null);
    }
  }, [panelOpen, panelTargetId]);

  // Portal target for DocCommentsRail: when rail is visible, portal the rail
  // component into the host-owned rail container div.
  const [railTarget, setRailTarget] = useState<Element | null>(null);
  useEffect(() => {
    if (railVisible && railTargetId) {
      const el = document.getElementById(railTargetId);
      setRailTarget(el);
    } else {
      setRailTarget(null);
    }
  }, [railVisible, railTargetId]);

  // "Aa" popover: portal a FormattingToolbar into the host-owned popover div
  // while open (same portal pattern as the panel/rail targets below).
  const formatOpen = props.formatPopoverOpen ?? false;
  const formatTargetId = props.formatPopoverTargetId;
  const [formatTarget, setFormatTarget] = useState<Element | null>(null);
  useEffect(() => {
    if (formatOpen && formatTargetId) {
      setFormatTarget(document.getElementById(formatTargetId));
    } else {
      setFormatTarget(null);
    }
  }, [formatOpen, formatTargetId]);

  const menus: ReactNode = (
    <>
      {/* Custom "/" menu: defaults trimmed to the app command set + callout. */}
      <SuggestionMenuController
        triggerCharacter="/"
        getItems={(query) => getFilteredDocSlashMenuItems(editor, features, query)}
      />
      {features.mentions && (
        <SuggestionMenuController
          triggerCharacter="@"
          getItems={(query) => getMentionMenuItems(editor, query)}
        />
      )}
      <FormattingToolbarController />
      {/* "Aa" popover: standard text options applying to the current
          selection/caret. Coexists with the floating toolbar. */}
      {formatTarget &&
        createPortal(
          <FormattingToolbar>
            <BlockTypeSelect />
            <BasicTextStyleButton basicTextStyle="bold" />
            <BasicTextStyleButton basicTextStyle="italic" />
            <BasicTextStyleButton basicTextStyle="underline" />
            <BasicTextStyleButton basicTextStyle="strike" />
            <ColorStyleButton />
            <CreateLinkButton />
          </FormattingToolbar>,
          formatTarget,
        )
      }
      {/* Inline comment floating UI — only active when CommentsExtension is
          wired (i.e. props.comments is set and mode is collab).
          FloatingComposerController: new-thread composer floating above selection.
          FloatingThreadController: selected-thread popover anchored to the mark.
          Both receive portalElement=floatingRootRef.current so they portal into
          the .dali-doc wrapper — this is what makes clicks inside the composer
          NOT trigger useDismiss's outside-press detection. */}
      {hasComments && (
        <FloatingComposerController portalElement={floatingRootRef.current ?? undefined} />
      )}
      {/* FloatingThreadController: mark clicks open an anchored thread popover.
          Suppressed when the rail is visible — the rail replaces the popover.
          focusManagerProps.disabled=false enables Floating UI's focus trap so
          the reply box receives focus when the popover opens. */}
      {hasComments && !railVisible && (
        <FloatingThreadController
          portalElement={floatingRootRef.current ?? undefined}
          floatingUIOptions={{ focusManagerProps: { disabled: false } }}
        />
      )}
      {/* ThreadsSidebar portaled into the panel when it's open. Stays inside
          the BlockNoteView context (required for editor/store access). */}
      {hasComments && panelTarget &&
        createPortal(
          // panelFilter mirrors the panel's Open/Resolved tab; fall back to
          // "open" when the panel is newly opened (no tab state yet).
          <ThreadsSidebar filter={props.comments?.panelFilter ?? "open"} sort="position" />,
          panelTarget,
        )
      }
      {/* DocCommentsRail portaled into the host-owned rail container when wide. */}
      {hasComments && railVisible && railTarget && editorContentRef &&
        createPortal(
          <DocCommentsRail
            filter={props.comments?.panelFilter ?? "open"}
            onFilterChange={props.comments?.onRailFilterChange ?? (() => {})}
            editorContentRef={editorContentRef}
            focusCommentId={props.comments?.focusCommentId}
          />,
          railTarget,
        )
      }
    </>
  );

  return (
    <SigningContext.Provider value={props.signing ?? DEFAULT_SIGNING_CTX}>
      <div
        ref={viewRef}
        className={[
          "dali-doc",
          props.density === "compact" ? "dali-doc--compact" : "",
          props.className ?? "",
        ]
          .filter(Boolean)
          .join(" ")}
      >
        {/* Floating portal root — must be INSIDE .dali-doc so useDismiss sees
            composer clicks as within-editor. Size/position are irrelevant; the
            floating UI positions itself via Floating UI's own logic. */}
        <div ref={floatingRootRef} className="dali-doc-floating-root" />

        <BlockNoteView
          editor={editor}
          // String theme only: BlockNote's default follows the SYSTEM color
          // scheme, but the app's dark mode is html.dark (user-overridable).
          theme={isDark ? "dark" : "light"}
          editable={props.editable ?? true}
          slashMenu={false}
          emojiPicker={false}
          // Compact fields don't need the drag-handle side menu (and its wide
          // gutter — see .dali-doc--compact in theme.css).
          sideMenu={props.density !== "compact"}
          // Disable BlockNoteDefaultUI's built-in formatting toolbar — we
          // mount FormattingToolbarController manually as a child (plus the
          // "Aa" popover portal in menus).
          formattingToolbar={false}
          // Disable BlockNoteDefaultUI's built-in comments controllers — we
          // mount FloatingComposerController and FloatingThreadController
          // manually as children (with our portalElement override).
          comments={false}
        >
          {menus}
        </BlockNoteView>
      </div>
    </SigningContext.Provider>
  );
}

/** onChange + throttled word count / H1–H3 outline (400ms, matching legacy).
 * editor.onChange also fires for remote collab transactions, so live peers'
 * edits keep the pages chrome fresh. */
function useDocChrome(
  editor: DocEditorInstance,
  props: Pick<DocEditorProps, "onChange" | "onWordCountChange" | "onHeadingsChange">,
) {
  const onChangeRef = useRef(props.onChange);
  const onWordCountRef = useRef(props.onWordCountChange);
  const onHeadingsRef = useRef(props.onHeadingsChange);
  onChangeRef.current = props.onChange;
  onWordCountRef.current = props.onWordCountChange;
  onHeadingsRef.current = props.onHeadingsChange;

  useEffect(() => {
    let timer: ReturnType<typeof setTimeout> | null = null;
    const computeChrome = () => {
      const blocks = editor.document;
      onWordCountRef.current?.(countWords(blocks));
      onHeadingsRef.current?.(extractHeadings(blocks));
    };
    const wantChrome = () => onWordCountRef.current || onHeadingsRef.current;

    const unsubscribe = editor.onChange(() => {
      onChangeRef.current?.(editor.document);
      if (!wantChrome() || timer) return;
      timer = setTimeout(() => {
        timer = null;
        computeChrome();
      }, 400);
    });
    if (wantChrome()) computeChrome();

    return () => {
      if (timer) clearTimeout(timer);
      unsubscribe?.();
    };
  }, [editor]);
}

function useDocSchema(features: Features) {
  return useMemo(
    () => buildSchema(features),
    // Individual flags, not the object: hosts typically pass a fresh literal
    // every render and a schema rebuild recreates the whole editor.
    [features.mentions, features.images, features.richBlocks, Boolean(features.signing)],
  );
}

function useDocDictionary(placeholder: string | undefined) {
  return useMemo(() => {
    if (!placeholder) return en;
    // Only the empty-document placeholder is overridden; per-block "type /"
    // hints keep BlockNote's defaults.
    return { ...en, placeholders: { ...en.placeholders, emptyDocument: placeholder } };
  }, [placeholder]);
}

/** Tracks the app's html.dark class (set by ~/lib/theme applyTheme — covers
 * user preference, system changes, and cross-iframe sync). */
function useIsDark(): boolean {
  const subscribe = useCallback((onChange: () => void) => {
    const observer = new MutationObserver(onChange);
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class"],
    });
    return () => observer.disconnect();
  }, []);
  return useSyncExternalStore(
    subscribe,
    () => document.documentElement.classList.contains("dark"),
    () => false,
  );
}
