-- Intentionally empty. Originally dropped DomainLeadAssignment.termId, but
-- the v0 schema rollback removed the termId column from the prior migration
-- entirely, so there is nothing left to drop. The (memberId, domainId) unique
-- and (domainId) index that this migration used to add are now created in
-- 20260512000000_calendar_v0_schema instead.
--
-- File preserved (not deleted) to keep migration-check.yml's "no deleted
-- migrations" guarantee.
