import { vi } from "vitest";

// Stub of the Prisma namespace re-exported from the real ~/lib/db. Only the
// JSON-null sentinels are referenced by callers (e.g. forms-data clearing a
// Json? column); they're identity-compared, so a stable stub object suffices.
export const Prisma = {
  DbNull: Symbol.for("Prisma.DbNull"),
  JsonNull: Symbol.for("Prisma.JsonNull"),
};

export const prisma = {
  user: {
    findUnique: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  session: {
    create: vi.fn(),
    findUnique: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
  },
  oAuthSession: {
    create: vi.fn(),
    findUnique: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
  },
  interviewConfig: {
    findUnique: vi.fn(),
  },
  cycleReviewer: {
    findMany: vi.fn(),
  },
  interviewAssignment: {
    findUnique: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
  },
  interview: {
    create: vi.fn(),
    update: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  application: {
    findUnique: vi.fn(),
  },
  applicationCycleStatusUpdate: {
    findFirst: vi.fn(),
  },
  auditLog: {
    create: vi.fn(),
  },
  confidentialityAgreement: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  cycleConfidentialityAgreement: {
    findUnique: vi.fn().mockResolvedValue({ confidentialityAgreementVersionId: "mock-cav-id" }),
  },
  confidentialityAgreementSignature: {
    findUnique: vi.fn().mockResolvedValue({ confidentialityAgreementVersionId: "mock-cav-id" }),
    count: vi.fn().mockResolvedValue(0),
  },
  oAuthClient: {
    findUnique: vi.fn(),
  },
  oAuthGrant: {
    findUnique: vi.fn(),
    upsert: vi.fn(),
    update: vi.fn(),
  },
  dALIMember: {
    findUnique: vi.fn(),
  },
  partnerUser: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  partnerOrg: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  projectPartner: {
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  partnerInvite: {
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    updateMany: vi.fn().mockResolvedValue({ count: 0 }),
  },
  notification: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
    create: vi.fn(),
    createMany: vi.fn(),
    createManyAndReturn: vi.fn().mockResolvedValue([]),
    update: vi.fn(),
    updateMany: vi.fn(),
  },
  notificationPreference: {
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
  },
  scheduledJob: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    create: vi.fn(),
    createMany: vi.fn().mockResolvedValue({ count: 0 }),
    update: vi.fn(),
    updateMany: vi.fn().mockResolvedValue({ count: 0 }),
    upsert: vi.fn(),
    deleteMany: vi.fn(),
  },
  projectAssignment: {
    findMany: vi.fn().mockResolvedValue([]),
    findFirst: vi.fn(),
  },
  project: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  sprint: {
    findMany: vi.fn().mockResolvedValue([]),
    findFirst: vi.fn(),
    findUnique: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
    delete: vi.fn(),
  },
  epic: {
    findFirst: vi.fn(),
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
    delete: vi.fn(),
  },
  userStory: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
  },
  task: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
    delete: vi.fn(),
    aggregate: vi.fn(),
    groupBy: vi.fn().mockResolvedValue([]),
    count: vi.fn().mockResolvedValue(0),
  },
  taskAssignee: {
    createMany: vi.fn(),
    deleteMany: vi.fn(),
  },
  taskComment: {
    create: vi.fn(),
    deleteMany: vi.fn(),
  },
  page: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
  },
  projectFile: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  scheduledMeeting: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
  },
  form: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  formVersion: {
    findFirst: vi.fn(),
    create: vi.fn(),
  },
  formFolder: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  groupDefinition: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
  },
  domainEligibility: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  userAvailabilitySettings: {
    findUnique: vi.fn().mockResolvedValue(null),
  },
  workingHoursDay: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  manualBlock: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  userCalendarLink: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    update: vi.fn(),
  },
  term: {
    findFirst: vi.fn().mockResolvedValue(null),
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  adminMembership: {
    findUnique: vi.fn(),
  },
  jobCodeLookup: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  coreAssignment: {
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
  },
  domainLeadAssignment: {
    findFirst: vi.fn(),
  },
  instructorAssignment: {
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    createMany: vi.fn(),
    deleteMany: vi.fn(),
  },
  educationOffering: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  educationSession: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
  },
  educationApplication: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    updateMany: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
    groupBy: vi.fn().mockResolvedValue([]),
  },
  educationAttendance: {
    findMany: vi.fn().mockResolvedValue([]),
    findUnique: vi.fn(),
    upsert: vi.fn(),
    deleteMany: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
  },
  educationAssignment: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  educationSubmission: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
    update: vi.fn(),
  },
  educationAnnouncement: {
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
  },
  educationDiscussionPost: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  educationStudentNote: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
  },
  educationCertificate: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    createMany: vi.fn(),
  },
  educationDecisionEmail: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
    delete: vi.fn(),
  },
  educationFormBinding: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    upsert: vi.fn(),
    delete: vi.fn(),
  },
  cECredit: {
    findUnique: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    upsert: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
    groupBy: vi.fn().mockResolvedValue([]),
  },
  formSubmission: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
  },
  emailTemplate: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  emailTemplateVersion: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
  },
  payPeriod: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    upsert: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
  },
  timesheetEntry: {
    findMany: vi.fn().mockResolvedValue([]),
    findFirst: vi.fn(),
    createMany: vi.fn(),
    deleteMany: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
    groupBy: vi.fn().mockResolvedValue([]),
    aggregate: vi.fn(),
  },
  timesheetNote: {
    findMany: vi.fn().mockResolvedValue([]),
    findFirst: vi.fn(),
    createMany: vi.fn(),
    deleteMany: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
  },
  timesheetImport: {
    findMany: vi.fn().mockResolvedValue([]),
    findFirst: vi.fn(),
    create: vi.fn(),
    deleteMany: vi.fn(),
  },
  budgetEntry: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    upsert: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
  },
  budgetNote: {
    findUnique: vi.fn(),
    findFirst: vi.fn(),
    findMany: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    upsert: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    deleteMany: vi.fn(),
  },
  $transaction: vi.fn(),
  $queryRaw: vi.fn().mockResolvedValue([]),
};
