// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.
import './Glows.css'

/** Blue corner glows and the warm glow around the rocket fire. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Glows({
  className,
  preserveAspectRatio,
}: {
  className?: string
  preserveAspectRatio?: string
}) {
  return (
    <svg
      viewBox="0 0 4075 1545"
      preserveAspectRatio={preserveAspectRatio}
      overflow="visible"
      fill="none"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <g transform="translate(-380.509 -105.001)">
        <g id="lp-Corner_Ambient_Glow" opacity="0.916489" filter="url(#lp-filter28_f_2445_3762)" transform="translate(308.51 1163)">
          <ellipse cx="450" cy="350" rx="450" ry="350" fill="#2680B3" fillOpacity="0.25" />
        </g>
        <g id="lp-Corner_Inner_Glow" opacity="0.816801" filter="url(#lp-filter29_f_2445_3762)" transform="translate(129.505 807.001)">
          <ellipse cx="250" cy="200" rx="250" ry="200" fill="#40A6D9" fillOpacity="0.2" />
        </g>
        <g id="lp-Fire_Glow" opacity="0.650332" filter="url(#lp-filter30_f_2445_3762)" transform="translate(459.509 1074)">
          <circle cx="150" cy="150" r="150" fill="#E6B359" fillOpacity="0.12" />
        </g>
      </g>
      <defs>
        <filter id="lp-filter28_f_2445_3762" x="-120" y="-120" width="1140" height="940" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="60" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter29_f_2445_3762" x="-80" y="-80" width="660" height="560" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="40" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter30_f_2445_3762" x="-57.5951" y="-57.5951" width="415.19" height="415.191" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="30" result="effect1_foregroundBlur_2445_3762" />
        </filter>
      </defs>
    </svg>
  )
}
