// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.
import src from '~/assets/landing/moon.svg'

/** The textured moon. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Moon({ className }: { className?: string }) {
  return (
    <img
      src={src}
      alt=""
      draggable={false}
      className={className}
      style={{ top: '-10.3560%', height: '110.3560%' }}
    />
  )
}
