// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.

/** Soft nebula glows behind the launch. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Nebula({
  className,
  preserveAspectRatio,
}: {
  className?: string
  preserveAspectRatio?: string
}) {
  return (
    <svg
      viewBox="0 0 4075 1545"
      preserveAspectRatio={preserveAspectRatio}
      overflow="visible"
      fill="none"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <g transform="translate(-380.509 -105.001)">
        <g transform="translate(380.509 105.001)">
          <g filter="url(#lp-filter7_f_2445_3762)" transform="translate(164 892)">
            <ellipse cx="250" cy="196.429" rx="250" ry="196.429" fill="#7B1A66" fillOpacity="0.34902" />
          </g>
          <g filter="url(#lp-filter8_f_2445_3762)" transform="translate(100 1150)">
            <ellipse cx="250" cy="190" rx="250" ry="190" fill="#3B1A80" fillOpacity="0.34902" />
          </g>
          <g filter="url(#lp-filter9_f_2445_3762)" transform="translate(500 1250)">
            <ellipse cx="200" cy="140" rx="200" ry="140" fill="#0D5A99" fillOpacity="0.4" />
          </g>
          <g filter="url(#lp-filter10_f_2445_3762)" transform="translate(550 1400)">
            <ellipse cx="125" cy="90" rx="125" ry="90" fill="#103080" fillOpacity="0.301961" />
          </g>
          <g filter="url(#lp-filter11_f_2445_3762)" transform="translate(350 1350)">
            <ellipse cx="150" cy="115" rx="150" ry="115" fill="#3B1A80" fillOpacity="0.25098" />
          </g>
        </g>
      </g>
      <defs>
        <filter id="lp-filter10_f_2445_3762" x="-40" y="-40" width="330" height="260" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="20" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter11_f_2445_3762" x="-55" y="-55" width="410" height="340" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="27.5" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter7_f_2445_3762" x="-78.5714" y="-78.5714" width="657.143" height="549.998" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="39.2857" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter8_f_2445_3762" x="-70" y="-70" width="640" height="520" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="35" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter9_f_2445_3762" x="-60" y="-60" width="520" height="400" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="30" result="effect1_foregroundBlur_2445_3762" />
        </filter>
      </defs>
    </svg>
  )
}
