// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.
import './Sky.css'

/** Background gradient, twinkling stars, distant planet and shooting stars. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Sky({
  className,
  preserveAspectRatio,
}: {
  className?: string
  preserveAspectRatio?: string
}) {
  return (
    <svg
      viewBox="0 0 4075 1545"
      preserveAspectRatio={preserveAspectRatio}
      overflow="visible"
      fill="none"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <g transform="translate(-380.509 -105.001)">
        <path transform="translate(380.51 106.001)" d="M4075 0H0V1544H4075V0Z" fill="url(#lp-paint0_linear_2445_3762)" />
        <g transform="translate(380.509 105.001)">
          <circle id="lp-star" opacity="0.566721" transform="translate(337.017 43.2383)" cx="1.74778" cy="1.74778" r="1.74778" fill="#C4B07E" />
          <circle id="lp-star_2" opacity="0.494472" transform="translate(1199.93 49.1061)" cx="1.98035" cy="1.98035" r="1.98035" fill="#A3ADA9" />
          <circle id="lp-star_3" opacity="0.287958" transform="translate(483.118 55.0737)" cx="1.20986" cy="1.20986" r="1.20986" fill="#C8A778" />
          <circle id="lp-star_4" opacity="0.260649" transform="translate(1321.56 83.9298)" cx="1.93376" cy="1.93376" r="1.93376" fill="#B59E66" />
          <circle id="lp-star_5" opacity="0.330266" transform="translate(584.876 92.9351)" cx="1.45681" cy="1.45681" r="1.45681" fill="#9595C7" />
          <circle id="lp-star_6" opacity="0.206306" transform="translate(1389.16 106.663)" cx="1.78244" cy="1.78244" r="1.78244" fill="#91ACB2" />
          <circle id="lp-star_7" opacity="0.402475" transform="translate(1066.55 198.235)" cx="1.59631" cy="1.59631" r="1.59631" fill="#C89C6E" />
          <circle id="lp-star_8" opacity="0.463314" transform="translate(1208.02 110.081)" cx="1.7001" cy="1.7001" r="1.7001" fill="#C8AA67" />
          <circle id="lp-star_9" opacity="0.380778" transform="translate(889.491 228.782)" cx="1.27112" cy="1.27112" r="1.27112" fill="#BCBB6C" />
          <circle id="lp-star_10" opacity="0.321006" transform="translate(1113.52 274.403)" cx="1.78242" cy="1.78242" r="1.78242" fill="#E5B178" />
          <circle id="lp-star_11" opacity="0.30324" transform="translate(1132.1 294.06)" cx="1.6589" cy="1.6589" r="1.6589" fill="#A4A5B7" />
          <circle id="lp-star_12" opacity="0.298527" transform="translate(1209.7 348.661)" cx="1.38715" cy="1.38715" r="1.38715" fill="#E59972" />
          <circle id="lp-star_13" opacity="0.591811" transform="translate(979.8 404.042)" cx="1.26687" cy="1.26687" r="1.26687" fill="#CB9A85" />
          <circle id="lp-star_14" opacity="0.250893" transform="translate(1042.43 474.905)" cx="1.73116" cy="1.73116" r="1.73116" fill="#D9B070" />
          <circle id="lp-star_15" opacity="0.359293" transform="translate(1032.63 484.381)" cx="1.99737" cy="1.99737" r="1.99737" fill="#9EB0AB" />
          <circle id="lp-star_16" opacity="0.300367" transform="translate(774.162 492.065)" cx="1.01388" cy="1.01388" r="1.01388" fill="#CC9D74" />
          <g filter="url(#lp-filter0_f_2445_3762)" transform="translate(1012.08 120.728)">
            <circle cx="9.07894" cy="9.07894" r="9.07894" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star" opacity="0.473906" transform="translate(1018.89 127.538)" cx="2.26974" cy="2.26974" r="2.26974" fill="#D9D1B3" />
          <circle id="lp-star_17" opacity="0.370993" transform="translate(1239.22 549.349)" cx="1.47556" cy="1.47556" r="1.47556" fill="#B5B97D" />
          <circle id="lp-star_18" opacity="0.203986" transform="translate(1217.23 593.995)" cx="0.83539" cy="0.83539" r="0.83539" fill="#E3AD72" />
          <circle id="lp-star_19" opacity="0.121229" transform="translate(203.485 136.983)" cx="0.843728" cy="0.843728" r="0.843728" fill="#BFBF8A" />
          <g filter="url(#lp-filter1_f_2445_3762)" transform="translate(1412.7 160.671)">
            <circle cx="13.6582" cy="13.6582" r="13.6582" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star_2" opacity="0.630188" transform="translate(1422.95 170.914)" cx="3.41456" cy="3.41456" r="3.41456" fill="#D9D1B3" />
          <circle id="lp-star_20" opacity="0.205053" transform="translate(1778.82 414.557)" cx="0.777247" cy="0.777247" r="0.777247" fill="#D1AA73" />
          <circle id="lp-star_21" opacity="0.627506" transform="translate(1834.24 723.748)" cx="1.92908" cy="1.92908" r="1.92908" fill="#CA9C7E" />
          <circle id="lp-star_22" opacity="0.273817" transform="translate(1858.84 328.708)" cx="1.49468" cy="1.49468" r="1.49468" fill="#D69E7E" />
          <circle id="lp-star_23" opacity="0.2545" transform="translate(2226.84 468.541)" cx="1.99432" cy="1.99432" r="1.99432" fill="#DF9E7E" />
          <circle id="lp-star_24" opacity="0.519581" transform="translate(1579.28 465.688)" cx="1.82873" cy="1.82873" r="1.82873" fill="#C1BD82" />
          <circle id="lp-star_25" opacity="0.168302" transform="translate(1889.21 894.796)" cx="0.758673" cy="0.758673" r="0.758673" fill="#93A4A9" />
          <circle id="lp-star_26" opacity="0.177034" transform="translate(2111.49 758.507)" cx="1.83984" cy="1.83984" r="1.83984" fill="#939BAC" />
          <circle id="lp-star_27" opacity="0.26594" transform="translate(2017.25 358.212)" cx="1.56552" cy="1.56552" r="1.56552" fill="#948FAD" />
          <circle id="lp-star_28" opacity="0.615605" transform="translate(1579.23 683.57)" cx="1.98773" cy="1.98773" r="1.98773" fill="#B9AD7A" />
          <circle id="lp-star_29" opacity="0.524721" transform="translate(1862.73 857.826)" cx="1.88367" cy="1.88367" r="1.88367" fill="#DCBD6A" />
          <circle id="lp-star_30" opacity="0.480952" transform="translate(2389.44 324.438)" cx="0.959714" cy="0.959714" r="0.959714" fill="#A1A3BC" />
          <circle id="lp-star_31" opacity="0.436157" transform="translate(2181.61 573.092)" cx="1.15688" cy="1.15688" r="1.15688" fill="#97AEC1" />
          <g filter="url(#lp-filter2_f_2445_3762)" transform="translate(2292.14 426.274)">
            <circle cx="12.3856" cy="12.3856" r="12.3856" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star_3" opacity="0.602208" transform="translate(2301.43 435.563)" cx="3.09641" cy="3.09641" r="3.09641" fill="#D9D1B3" />
          <circle id="lp-star_32" opacity="0.204636" transform="translate(2412.55 459.281)" cx="1.89966" cy="1.89966" r="1.89966" fill="#C29F69" />
          <g filter="url(#lp-filter3_f_2445_3762)" transform="translate(2179.16 249.484)">
            <circle cx="12.5306" cy="12.5306" r="12.5306" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star_4" opacity="0.350332" transform="translate(2188.55 258.882)" cx="3.13265" cy="3.13265" r="3.13265" fill="#D9D1B3" />
          <g id="lp-Distant_Planet" opacity="0.437367" filter="url(#lp-filter4_d_2445_3762)" transform="translate(2050 200)">
            <circle cx="22.5" cy="22.5" r="22.5" fill="#2E2640" />
          </g>
          <circle id="lp-star_33" opacity="0.461696" transform="translate(2142.37 1066.49)" cx="1.62695" cy="1.62695" r="1.62695" fill="#D8AE72" />
          <circle id="lp-star_34" opacity="0.605386" transform="translate(2075.47 1129.17)" cx="1.6242" cy="1.6242" r="1.6242" fill="#CABD74" />
          <circle id="lp-star_35" opacity="0.300198" transform="translate(2279.02 1139.39)" cx="1.73412" cy="1.73412" r="1.73412" fill="#C9B369" />
          <circle id="lp-star_36" opacity="0.219256" transform="translate(2088.58 1173.86)" cx="1.03774" cy="1.03774" r="1.03774" fill="#D2A583" />
          <circle id="lp-star_37" opacity="0.620218" transform="translate(449.368 251.682)" cx="0.860927" cy="0.860927" r="0.860927" fill="#D2B88B" />
          <circle id="lp-star_38" opacity="0.615637" transform="translate(142.597 259.885)" cx="1.58836" cy="1.58836" r="1.58836" fill="#B8AF7E" />
          <circle id="lp-star_39" opacity="0.161146" transform="translate(245.833 280.099)" cx="1.30953" cy="1.30953" r="1.30953" fill="#BFB668" />
          <circle id="lp-star_40" opacity="0.33759" transform="translate(1310.2 362.267)" cx="0.908284" cy="0.908284" r="0.908284" fill="#C4B970" />
          <circle id="lp-star_41" opacity="0.156069" transform="translate(424.45 385.349)" cx="1.65058" cy="1.65058" r="1.65058" fill="#9A8EB7" />
          <circle id="lp-star_42" opacity="0.428217" transform="translate(164.287 428.719)" cx="1.74639" cy="1.74639" r="1.74639" fill="#BEAF79" />
          <circle id="lp-star_43" opacity="0.257357" transform="translate(225.499 539.83)" cx="1.26316" cy="1.26316" r="1.26316" fill="#B9A070" />
          <circle id="lp-star_44" opacity="0.349642" transform="translate(187.321 568.954)" cx="0.772703" cy="0.772703" r="0.772703" fill="#E0A572" />
          <circle id="lp-star_45" opacity="0.491504" transform="translate(406.895 590.199)" cx="1.23084" cy="1.23084" r="1.23084" fill="#BDA58C" />
          <circle id="lp-star_46" opacity="0.514665" transform="translate(1412.05 414.311)" cx="0.94288" cy="0.94288" r="0.94288" fill="#8FA7AD" />
          <circle id="lp-star_47" opacity="0.265552" transform="translate(1321.32 455.851)" cx="1.41157" cy="1.41157" r="1.41157" fill="#849FB2" />
          <circle id="lp-star_48" opacity="0.239257" transform="translate(645.074 512.555)" cx="1.0076" cy="1.0076" r="1.0076" fill="#C29C7E" />
          <circle id="lp-star_49" opacity="0.156157" transform="translate(2410.11 562.706)" cx="0.943797" cy="0.943797" r="0.943797" fill="#CAB870" />
          <circle id="lp-star_50" opacity="0.329502" transform="translate(540.093 557.253)" cx="1.01313" cy="1.01313" r="1.01313" fill="#CDB56B" />
          <circle id="lp-star_51" opacity="0.31546" transform="translate(1103.33 718.269)" cx="0.938647" cy="0.938647" r="0.938647" fill="#B6AD7B" />
          <circle id="lp-star_52" opacity="0.58885" transform="translate(1245.61 742.412)" cx="1.21053" cy="1.21053" r="1.21053" fill="#C29F75" />
          <circle id="lp-star_53" opacity="0.413877" transform="translate(1289.87 760.859)" cx="1.38891" cy="1.38891" r="1.38891" fill="#8892C7" />
          <g filter="url(#lp-filter5_f_2445_3762)" transform="translate(1405.15 780.756)">
            <circle cx="13.3924" cy="13.3924" r="13.3924" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star_5" opacity="0.555318" transform="translate(1415.19 790.801)" cx="3.3481" cy="3.3481" r="3.3481" fill="#D9D1B3" />
          <circle id="lp-star_54" opacity="0.284508" transform="translate(1392.2 790.572)" cx="1.08989" cy="1.08989" r="1.08989" fill="#DEA675" />
          <circle id="lp-star_55" opacity="0.322882" transform="translate(916.57 827.925)" cx="1.94844" cy="1.94844" r="1.94844" fill="#8B98C8" />
          <g filter="url(#lp-filter6_f_2445_3762)" transform="translate(1698.54 890.093)">
            <circle cx="8.30746" cy="8.30746" r="8.30746" fill="#B3B3D9" fillOpacity="0.12" />
          </g>
          <circle id="lp-bright-star_6" opacity="0.647887" transform="translate(1704.77 896.323)" cx="2.07687" cy="2.07687" r="2.07687" fill="#D9D1B3" />
          <circle id="lp-star_56" opacity="0.432412" transform="translate(1178.01 978.727)" cx="1.87176" cy="1.87176" r="1.87176" fill="#D6A779" />
          <circle id="lp-star_57" opacity="0.586582" transform="translate(1484.11 1024.93)" cx="0.941448" cy="0.941448" r="0.941448" fill="#8B9BCB" />
          <circle id="lp-star_58" opacity="0.210221" transform="translate(1251.85 1170.45)" cx="1.66632" cy="1.66632" r="1.66632" fill="#B8A780" />
          <circle id="lp-star_59" opacity="0.362443" transform="translate(1150.43 1180.43)" cx="1.6565" cy="1.6565" r="1.6565" fill="#B8B269" />
          <circle id="lp-star_60" opacity="0.337449" transform="translate(1626.8 1141.79)" cx="1.04859" cy="1.04859" r="1.04859" fill="#A4ACAB" />
          <circle opacity="0.62" transform="translate(2650 78)" cx="1.4" cy="1.4" r="1.4" fill="#C4B07E" />
          <circle opacity="0.55" transform="translate(2890 145)" cx="1.75" cy="1.75" r="1.75" fill="#A3ADA9" />
          <circle opacity="0.48" transform="translate(3100 62)" cx="1.05" cy="1.05" r="1.05" fill="#C8A778" />
          <circle opacity="0.38" transform="translate(3350 220)" cx="1.95" cy="1.95" r="1.95" fill="#B59E66" />
          <circle opacity="0.45" transform="translate(3520 90)" cx="1.25" cy="1.25" r="1.25" fill="#9595C7" />
          <circle opacity="0.4" transform="translate(3750 180)" cx="1.6" cy="1.6" r="1.6" fill="#91ACB2" />
          <circle opacity="0.65" transform="translate(3900 55)" cx="0.9" cy="0.9" r="0.9" fill="#C89C6E" />
          <circle opacity="0.58" transform="translate(4020 310)" cx="1.55" cy="1.55" r="1.55" fill="#C8AA67" />
          <circle opacity="0.5" transform="translate(2720 340)" cx="1.15" cy="1.15" r="1.15" fill="#BCBB6C" />
          <circle opacity="0.42" transform="translate(2980 480)" cx="1.85" cy="1.85" r="1.85" fill="#E5B178" />
          <circle opacity="0.55" transform="translate(3180 560)" cx="1.45" cy="1.45" r="1.45" fill="#A4A5B7" />
          <circle opacity="0.6" transform="translate(3420 430)" cx="1" cy="1" r="1" fill="#E59972" />
          <circle opacity="0.7" transform="translate(3680 620)" cx="1.7" cy="1.7" r="1.7" fill="#CB9A85" />
          <circle opacity="0.44" transform="translate(3850 390)" cx="1.35" cy="1.35" r="1.35" fill="#D9B070" />
          <circle opacity="0.38" transform="translate(4000 510)" cx="0.8" cy="0.8" r="0.8" fill="#9EB0AB" />
          <g filter="url(#lp-filter12_f_2445_3762)" transform="translate(2840 200)">
            <circle cx="11" cy="11" r="11" fill="#B2B2D9" fillOpacity="0.121569" />
          </g>
          <circle opacity="0.7" transform="translate(2848 208)" cx="2.75" cy="2.75" r="2.75" fill="#D9D1B2" />
          <circle opacity="0.5" transform="translate(2600 700)" cx="1.1" cy="1.1" r="1.1" fill="#B5B97D" />
          <circle opacity="0.48" transform="translate(2760 820)" cx="1.8" cy="1.8" r="1.8" fill="#E3AD72" />
          <circle opacity="0.35" transform="translate(3050 755)" cx="0.95" cy="0.95" r="0.95" fill="#BFBF8A" />
          <circle opacity="0.55" transform="translate(3310 890)" cx="1.5" cy="1.5" r="1.5" fill="#D1AA73" />
          <circle opacity="0.7" transform="translate(3580 810)" cx="1.25" cy="1.25" r="1.25" fill="#CA9C7E" />
          <circle opacity="0.58" transform="translate(3780 940)" cx="1.9" cy="1.9" r="1.9" fill="#D69E7E" />
          <circle opacity="0.42" transform="translate(3960 860)" cx="1.05" cy="1.05" r="1.05" fill="#DF9E7E" />
          <g filter="url(#lp-filter13_f_2445_3762)" transform="translate(3240 630)">
            <circle cx="14" cy="14" r="14" fill="#B2B2D9" fillOpacity="0.121569" />
          </g>
          <circle opacity="0.7" transform="translate(3250 640)" cx="3.5" cy="3.5" r="3.5" fill="#D9D1B2" />
          <circle opacity="0.6" transform="translate(2640 1050)" cx="1.4" cy="1.4" r="1.4" fill="#C1BD82" />
          <circle opacity="0.5" transform="translate(2900 1130)" cx="0.85" cy="0.85" r="0.85" fill="#93A4A9" />
          <circle opacity="0.38" transform="translate(3150 1080)" cx="1.75" cy="1.75" r="1.75" fill="#939BAC" />
          <circle opacity="0.45" transform="translate(3400 1180)" cx="1.2" cy="1.2" r="1.2" fill="#948FAD" />
          <circle opacity="0.65" transform="translate(3700 1090)" cx="1.55" cy="1.55" r="1.55" fill="#B9AD7A" />
          <circle opacity="0.5" transform="translate(3900 1200)" cx="1" cy="1" r="1" fill="#DCBD6A" />
          <circle opacity="0.7" transform="translate(4050 1100)" cx="0.75" cy="0.75" r="0.75" fill="#A1A3BC" />
          <circle id="lp-background-star-added-1" opacity="0.428217" transform="translate(1620 1286.23)" cx="1.37338" cy="1.37338" r="1.37338" fill="#BEAF79" />
          <circle opacity="0.42" transform="translate(3589.61 1115.89)" cx="1.31985" cy="1.31985" r="1.31985" fill="#D9B070" />
          <circle opacity="0.42" transform="translate(729.549 1230.74)" cx="2.04524" cy="2.04524" r="2.04524" fill="#A3ADA9" />
          <circle opacity="0.591538" transform="translate(566.007 247.52)" cx="1.44999" cy="1.44999" r="1.44999" fill="#C4B07E" />
          <circle opacity="0.482205" transform="translate(2832.84 1274.76)" cx="1.6597" cy="1.6597" r="1.6597" fill="#A4A5B7" />
          <circle id="lp-background-star-added-6" opacity="0.519581" transform="translate(634.062 913.017)" cx="1.94926" cy="1.94926" r="1.94926" fill="#C1BD82" />
          <circle opacity="0.472568" transform="translate(761.539 1101.33)" cx="0.91032" cy="0.91032" r="0.91032" fill="#E59972" />
          <circle opacity="0.42" transform="translate(2827.84 1036.06)" cx="1.88804" cy="1.88804" r="1.88804" fill="#E5B178" />
          <circle id="lp-background-star-added-9" opacity="0.461696" transform="translate(2938.14 1020.33)" cx="1.75117" cy="1.75117" r="1.75117" fill="#D8AE72" />
          <circle id="lp-background-star-added-10" opacity="0.205053" transform="translate(625.019 1017.22)" cx="0.802769" cy="0.802769" r="0.802769" fill="#D1AA73" />
          <circle id="lp-background-star-added-11" opacity="0.329502" transform="translate(342.437 1285.16)" cx="0.82604" cy="0.82604" r="0.82604" fill="#CDB56B" />
          <circle id="lp-background-star-added-12" opacity="0.615637" transform="translate(921.706 637.36)" cx="1.40766" cy="1.40766" r="1.40766" fill="#B8AF7E" />
          <circle id="lp-background-star-added-13" opacity="0.463314" transform="translate(3122.81 751.971)" cx="1.81541" cy="1.81541" r="1.81541" fill="#C8AA67" />
          <circle id="lp-background-star-added-14" opacity="0.627506" transform="translate(418.675 998.853)" cx="1.91626" cy="1.91626" r="1.91626" fill="#CA9C7E" />
          <circle id="lp-background-star-added-15" opacity="0.566721" transform="translate(3538.84 748.813)" cx="1.56659" cy="1.56659" r="1.56659" fill="#C4B07E" />
          <circle id="lp-background-star-added-16" opacity="0.156069" transform="translate(3028.05 992.409)" cx="1.48479" cy="1.48479" r="1.48479" fill="#9A8EB7" />
          <circle id="lp-background-star-added-17" opacity="0.203986" transform="translate(3275.61 124.609)" cx="0.975152" cy="0.975152" r="0.975152" fill="#E3AD72" />
          <circle id="lp-background-star-added-18" opacity="0.432412" transform="translate(1540.54 1441.11)" cx="2.189" cy="2.189" r="2.189" fill="#D6A779" />
          <circle opacity="0.42" transform="translate(326.101 656.149)" cx="1.88004" cy="1.88004" r="1.88004" fill="#E5B178" />
          <circle id="lp-background-star-added-20" opacity="0.413877" transform="translate(863.694 429.075)" cx="1.41972" cy="1.41972" r="1.41972" fill="#8892C7" />
          <circle opacity="0.487963" transform="translate(3409.02 340.201)" cx="0.714999" cy="0.714999" r="0.714999" fill="#A1A3BC" />
          <circle id="lp-background-star-added-22" opacity="0.461696" transform="translate(2366.19 1505.13)" cx="1.52513" cy="1.52513" r="1.52513" fill="#D8AE72" />
          <circle id="lp-background-star-added-23" opacity="0.436157" transform="translate(750.928 388.182)" cx="1.3229" cy="1.3229" r="1.3229" fill="#97AEC1" />
          <circle id="lp-background-star-added-24" opacity="0.519581" transform="translate(2667.8 1178.25)" cx="1.61502" cy="1.61502" r="1.61502" fill="#C1BD82" />
          <circle id="lp-background-star-added-25" opacity="0.436157" transform="translate(1695.78 415.051)" cx="1.23906" cy="1.23906" r="1.23906" fill="#97AEC1" />
          <circle id="lp-background-star-added-26" opacity="0.494472" transform="translate(941.278 155.685)" cx="1.68685" cy="1.68685" r="1.68685" fill="#A3ADA9" />
          <circle id="lp-background-star-added-27" opacity="0.121229" transform="translate(3503.72 856.797)" cx="0.893712" cy="0.893712" r="0.893712" fill="#BFBF8A" />
          <circle id="lp-background-star-added-28" opacity="0.330266" transform="translate(1981.89 154.764)" cx="1.45767" cy="1.45767" r="1.45767" fill="#9595C7" />
          <circle opacity="0.42" transform="translate(2000.12 1071.98)" cx="1.11198" cy="1.11198" r="1.11198" fill="#C8A778" />
          <circle opacity="0.42" transform="translate(3099.97 177.551)" cx="1.36226" cy="1.36226" r="1.36226" fill="#948FAD" />
          <circle id="lp-background-star-added-31" opacity="0.428217" transform="translate(871.63 985.85)" cx="1.45341" cy="1.45341" r="1.45341" fill="#BEAF79" />
          <circle opacity="0.439667" transform="translate(2654.9 1493.75)" cx="1.46474" cy="1.46474" r="1.46474" fill="#C4B07E" />
          <circle opacity="0.42" transform="translate(2179.37 40.751)" cx="0.967262" cy="0.967262" r="0.967262" fill="#BCBB6C" />
          <circle id="lp-background-star-added-34" opacity="0.287958" transform="translate(3548.49 1002.44)" cx="0.946572" cy="0.946572" r="0.946572" fill="#C8A778" />
          <circle id="lp-background-star-added-35" opacity="0.514665" transform="translate(127.819 1398.06)" cx="1.03483" cy="1.03483" r="1.03483" fill="#8FA7AD" />
          <circle opacity="0.42" transform="translate(167.96 850.526)" cx="1.0277" cy="1.0277" r="1.0277" fill="#B5B97D" />
          <circle opacity="0.42" transform="translate(84.0506 356.853)" cx="2.02502" cy="2.02502" r="2.02502" fill="#E5B178" />
          <circle opacity="0.58151" transform="translate(2430.51 137.267)" cx="1.09795" cy="1.09795" r="1.09795" fill="#C4B07E" />
          <g id="lp-Shooting_Star_1" opacity="0" transform="translate(1880 330) rotate(20)">
            <rect opacity="0.32" transform="translate(14 10)" width="310" height="8" rx="4" fill="url(#lp-paint1_linear_2445_3762)" />
            <rect transform="translate(88.2 12.8)" width="241.8" height="2.4" rx="1.2" fill="url(#lp-paint2_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(320 5)" cx="9" cy="9" r="9" fill="url(#lp-paint3_radial_2445_3762)" />
            <circle transform="translate(326.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_2" opacity="0" transform="translate(1280.72 1012) rotate(16)">
            <rect opacity="0.32" transform="translate(14 10)" width="250" height="8" rx="4" fill="url(#lp-paint4_linear_2445_3762)" />
            <rect transform="translate(75 12.8)" width="195" height="2.4" rx="1.2" fill="url(#lp-paint5_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(260 5)" cx="9" cy="9" r="9" fill="url(#lp-paint6_radial_2445_3762)" />
            <circle transform="translate(266.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_3" opacity="0" transform="translate(63.9405 43) rotate(23)">
            <rect opacity="0.32" transform="translate(14 10)" width="360" height="8" rx="4" fill="url(#lp-paint7_linear_2445_3762)" />
            <rect transform="translate(99.2 12.8)" width="280.8" height="2.4" rx="1.2" fill="url(#lp-paint8_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(370 5)" cx="9" cy="9" r="9" fill="url(#lp-paint9_radial_2445_3762)" />
            <circle transform="translate(376.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_4" opacity="0" transform="translate(1450 190) rotate(20)">
            <rect opacity="0.32" transform="translate(14 10)" width="310" height="8" rx="4" fill="url(#lp-paint10_linear_2445_3762)" />
            <rect transform="translate(88.2 12.8)" width="241.8" height="2.4" rx="1.2" fill="url(#lp-paint11_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(320 5)" cx="9" cy="9" r="9" fill="url(#lp-paint12_radial_2445_3762)" />
            <circle transform="translate(326.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_5" opacity="0" transform="translate(2220 860) rotate(16)">
            <rect opacity="0.32" transform="translate(14 10)" width="250" height="8" rx="4" fill="url(#lp-paint13_linear_2445_3762)" />
            <rect transform="translate(75 12.8)" width="195" height="2.4" rx="1.2" fill="url(#lp-paint14_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(260 5)" cx="9" cy="9" r="9" fill="url(#lp-paint15_radial_2445_3762)" />
            <circle transform="translate(266.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_6" opacity="0" transform="translate(1011.94 1224) rotate(23)">
            <rect opacity="0.32" transform="translate(14 10)" width="360" height="8" rx="4" fill="url(#lp-paint16_linear_2445_3762)" />
            <rect transform="translate(99.2 12.8)" width="280.8" height="2.4" rx="1.2" fill="url(#lp-paint17_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(370 5)" cx="9" cy="9" r="9" fill="url(#lp-paint18_radial_2445_3762)" />
            <circle transform="translate(376.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_7" opacity="0.977424" transform="translate(1120 380) rotate(16)">
            <rect opacity="0.32" transform="translate(14 10)" width="250" height="8" rx="4" fill="url(#lp-paint19_linear_2445_3762)" />
            <rect transform="translate(75 12.8)" width="195" height="2.4" rx="1.2" fill="url(#lp-paint20_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(260 5)" cx="9" cy="9" r="9" fill="url(#lp-paint21_radial_2445_3762)" />
            <circle transform="translate(266.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_8" opacity="0" transform="translate(1420 690) rotate(20)">
            <rect opacity="0.32" transform="translate(14 10)" width="310" height="8" rx="4" fill="url(#lp-paint22_linear_2445_3762)" />
            <rect transform="translate(88.2 12.8)" width="241.8" height="2.4" rx="1.2" fill="url(#lp-paint23_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(320 5)" cx="9" cy="9" r="9" fill="url(#lp-paint24_radial_2445_3762)" />
            <circle transform="translate(326.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
          <g id="lp-Shooting_Star_9" opacity="0" transform="translate(614.94 804) rotate(23)">
            <rect opacity="0.32" transform="translate(14 10)" width="360" height="8" rx="4" fill="url(#lp-paint25_linear_2445_3762)" />
            <rect transform="translate(99.2 12.8)" width="280.8" height="2.4" rx="1.2" fill="url(#lp-paint26_linear_2445_3762)" />
            <circle opacity="0.25" transform="translate(370 5)" cx="9" cy="9" r="9" fill="url(#lp-paint27_radial_2445_3762)" />
            <circle transform="translate(376.7 11.2)" cx="2.75" cy="2.75" r="2.75" fill="white" />
          </g>
        </g>
      </g>
      <defs>
        <filter id="lp-filter0_f_2445_3762" x="-8" y="-8" width="34.1582" height="34.1562" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter12_f_2445_3762" x="-8" y="-8" width="38" height="38" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter13_f_2445_3762" x="-8" y="-8" width="44" height="44" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter1_f_2445_3762" x="-8" y="-8" width="43.3164" height="43.3164" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter2_f_2445_3762" x="-8" y="-8" width="40.7715" height="40.7695" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter3_f_2445_3762" x="-8" y="-8" width="41.0605" height="41.0625" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter4_d_2445_3762" x="-15" y="-15" width="75" height="75" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.2 0 0 0 0 0.15 0 0 0 0 0.35 0 0 0 0.25 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter5_f_2445_3762" x="-8" y="-8" width="42.7852" height="42.7852" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter6_f_2445_3762" x="-8" y="-8" width="32.6152" height="32.6133" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="4" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <linearGradient id="lp-paint0_linear_2445_3762" x1="241.601" y1="1544" x2="1729.74" y2="-251.827" gradientUnits="userSpaceOnUse">
          <stop stopColor="#0A0F24" />
          <stop offset="0.5" stopColor="#080A1A" />
          <stop offset="1" stopColor="#050812" />
        </linearGradient>
        <linearGradient id="lp-paint10_linear_2445_3762" x1="310" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint11_linear_2445_3762" x1="241.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint12_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint13_linear_2445_3762" x1="250" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint14_linear_2445_3762" x1="195" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint15_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint16_linear_2445_3762" x1="360" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint17_linear_2445_3762" x1="280.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint18_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint19_linear_2445_3762" x1="250" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint1_linear_2445_3762" x1="310" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint20_linear_2445_3762" x1="195" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint21_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint22_linear_2445_3762" x1="310" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint23_linear_2445_3762" x1="241.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint24_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint25_linear_2445_3762" x1="360" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint26_linear_2445_3762" x1="280.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint27_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint2_linear_2445_3762" x1="241.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint3_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint4_linear_2445_3762" x1="250" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint5_linear_2445_3762" x1="195" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint6_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
        <linearGradient id="lp-paint7_linear_2445_3762" x1="360" y1="4" x2="0" y2="4" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" stopOpacity="0.8" />
          <stop offset="0.18" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="lp-paint8_linear_2445_3762" x1="280.8" y1="1.2" x2="0" y2="1.2" gradientUnits="userSpaceOnUse">
          <stop stopColor="white" />
          <stop offset="0.12" stopColor="white" stopOpacity="0.92" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </linearGradient>
        <radialGradient id="lp-paint9_radial_2445_3762" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="scale(18)">
          <stop stopColor="white" stopOpacity="0.9" />
          <stop offset="0.35" stopColor="white" stopOpacity="0.3" />
          <stop offset="1" stopColor="white" stopOpacity="0" />
        </radialGradient>
      </defs>
    </svg>
  )
}
