// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.
import './Smoke.css'

/** Layered exhaust clouds with drifting bubbles. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Smoke({
  className,
  preserveAspectRatio,
}: {
  className?: string
  preserveAspectRatio?: string
}) {
  return (
    <svg
      viewBox="0 0 4075 1545"
      preserveAspectRatio={preserveAspectRatio}
      overflow="visible"
      fill="none"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <g transform="translate(-380.509 -105.001)">
        <g transform="translate(197.126 841.586)">
          <g className="landing-smoke-layer" style={{ animationDelay: 'calc(var(--enter-start) + 0ms)' }}>
            <g id="lp-wave_layer_4" opacity="0.937367">
              <g id="lp-wave_layer_4_bubble_10" filter="url(#lp-filter49_d_2445_3762)" transform="translate(299.376 115)">
                <path d="M28 56C43.464 56 56 43.464 56 28C56 12.536 43.464 0 28 0C12.536 0 0 12.536 0 28C0 43.464 12.536 56 28 56Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_9" filter="url(#lp-filter50_d_2445_3762)" transform="translate(776.376 608)">
                <path d="M33 66C51.2254 66 66 51.2254 66 33C66 14.7746 51.2254 0 33 0C14.7746 0 0 14.7746 0 33C0 51.2254 14.7746 66 33 66Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_8" filter="url(#lp-filter51_d_2445_3762)" transform="translate(426.376 448)">
                <path d="M47.5 95C73.7335 95 95 73.7335 95 47.5C95 21.2665 73.7335 0 47.5 0C21.2665 0 0 21.2665 0 47.5C0 73.7335 21.2665 95 47.5 95Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_7" filter="url(#lp-filter52_d_2445_3762)" transform="translate(388.376 394)">
                <path d="M38.5 77C59.763 77 77 59.763 77 38.5C77 17.237 59.763 0 38.5 0C17.237 0 0 17.237 0 38.5C0 59.763 17.237 77 38.5 77Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_6" filter="url(#lp-filter53_d_2445_3762)" transform="translate(384.376 302)">
                <path d="M52 104C80.7188 104 104 80.7188 104 52C104 23.2812 80.7188 0 52 0C23.2812 0 0 23.2812 0 52C0 80.7188 23.2812 104 52 104Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_5" filter="url(#lp-filter54_d_2445_3762)" transform="translate(368.376 241)">
                <path d="M47.5 95C73.7335 95 95 73.7335 95 47.5C95 21.2665 73.7335 0 47.5 0C21.2665 0 0 21.2665 0 47.5C0 73.7335 21.2665 95 47.5 95Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_4" filter="url(#lp-filter55_d_2445_3762)" transform="translate(698.376 512)">
                <path d="M65 130C100.899 130 130 100.899 130 65C130 29.1015 100.899 0 65 0C29.1015 0 0 29.1015 0 65C0 100.899 29.1015 130 65 130Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_3" filter="url(#lp-filter56_d_2445_3762)" transform="translate(771.376 641)">
                <path d="M63.5 127C98.5701 127 127 98.5701 127 63.5C127 28.4299 98.5701 0 63.5 0C28.4299 0 0 28.4299 0 63.5C0 98.5701 28.4299 127 63.5 127Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_2" filter="url(#lp-filter57_d_2445_3762)" transform="translate(244.376)">
                <path d="M20.5833 41.1667C31.9512 41.1667 41.1667 31.9512 41.1667 20.5833C41.1667 9.21548 31.9512 0 20.5833 0C9.21548 0 0 9.21548 0 20.5833C0 31.9512 9.21548 41.1667 20.5833 41.1667Z" fill="#41B8E1" />
              </g>
              <g id="lp-wave_layer_4_bubble_1" filter="url(#lp-filter58_d_2445_3762)" transform="translate(527.376 231.417)">
                <path d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24Z" fill="#41B8E1" />
              </g>
              <g filter="url(#lp-filter59_d_2445_3762)" transform="translate(216.377 282.048)">
                <path d="M229.5 198.368C169.332 117.924 253.038 63.9909 198 18.8683C142.558 -26.5859 14.5 24.3683 14.5 24.3683L0 259.951L432 372.951C432 372.951 518.953 315.349 515 268.368C506.562 168.072 289.784 278.968 229.5 198.368Z" fill="#41B8E1" />
                <path d="M229.5 198.368C169.332 117.924 253.038 63.9909 198 18.8683C142.558 -26.5859 14.5 24.3683 14.5 24.3683L0 259.951L432 372.951C432 372.951 518.953 315.349 515 268.368C506.562 168.072 289.784 278.968 229.5 198.368Z" stroke="#41B8E1" />
              </g>
              <g filter="url(#lp-filter60_d_2445_3762)" transform="translate(0 75.7939)">
                <path d="M870.876 732.706C866.509 618.69 886.376 549.206 727.376 478.206C568.376 407.206 438.376 463.206 417.376 416.206C396.376 369.206 371.143 205.253 369.449 191.52C366.397 166.881 364.204 151.471 362.863 145.323C358.701 126.237 354.617 111.243 350.633 100.32C343.032 79.552 333.108 61.5108 320.862 46.2296C303.062 24.0258 282.869 10.0597 251.861 3.40376C221.262 -3.16433 200.319 -0.471845 172.376 13.6226C134.3 34.8328 114.05 49.6827 82.3761 79.6227C-102.97 254.821 82.3761 732.706 82.3761 732.706V793.623H867.376C867.376 793.623 871.788 756.517 870.876 732.706Z" fill="#41B8E1" />
              </g>
            </g>
          </g>
          <g className="landing-smoke-layer" style={{ animationDelay: 'calc(var(--enter-start) + 110ms)' }}>
            <g id="lp-wave_layer_3" transform="translate(157.376 71)">
              <g id="lp-wave_layer_3_bubble_15" filter="url(#lp-filter61_d_2445_3762)" transform="translate(256)">
                <path d="M23.5 47C36.4787 47 47 36.4787 47 23.5C47 10.5213 36.4787 0 23.5 0C10.5213 0 0 10.5213 0 23.5C0 36.4787 10.5213 47 23.5 47Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_14" filter="url(#lp-filter62_d_2445_3762)" transform="translate(220 28)">
                <path d="M31 62C48.1208 62 62 48.1209 62 31C62 13.8792 48.1208 0 31 0C13.8792 0 0 13.8792 0 31C0 48.1209 13.8792 62 31 62Z" fill="#0C4B78" />
              </g>
              <path id="lp-wave_layer_3_bubble_13" transform="translate(205 259)" d="M23.5 47C36.4787 47 47 36.4787 47 23.5C47 10.5213 36.4787 0 23.5 0C10.5213 0 0 10.5213 0 23.5C0 36.4787 10.5213 47 23.5 47Z" fill="#0C4B78" />
              <g id="lp-wave_layer_3_bubble_12" filter="url(#lp-filter63_d_2445_3762)" transform="translate(139 200)">
                <path d="M70.5 141C109.436 141 141 109.436 141 70.5001C141 31.564 109.436 0 70.5 0C31.5639 0 0 31.564 0 70.5001C0 109.436 31.5639 141 70.5 141Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_11" filter="url(#lp-filter64_d_2445_3762)" transform="translate(213 72)">
                <path d="M17.5 35C27.165 35 35 27.165 35 17.5C35 7.83503 27.165 0 17.5 0C7.83502 0 0 7.83503 0 17.5C0 27.165 7.83502 35 17.5 35Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_10" filter="url(#lp-filter65_d_2445_3762)" transform="translate(142 82)">
                <path d="M53 106C82.2711 106 106 82.2711 106 53C106 23.7289 82.2711 0 53 0C23.7289 0 0 23.7289 0 53C0 82.2711 23.7289 106 53 106Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_9" filter="url(#lp-filter66_d_2445_3762)" transform="translate(513 570)">
                <path d="M53 106C82.2711 106 106 82.2711 106 53C106 23.7289 82.2711 0 53 0C23.7289 0 0 23.7289 0 53C0 82.2711 23.7289 106 53 106Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_8" filter="url(#lp-filter67_d_2445_3762)" transform="translate(105 315)">
                <path d="M74.5 149C115.645 149 149 115.645 149 74.5C149 33.3548 115.645 0 74.5 0C33.3548 0 0 33.3548 0 74.5C0 115.645 33.3548 149 74.5 149Z" fill="#0C4B78" />
              </g>
              <path id="lp-wave_layer_3_bubble_7" transform="translate(105 283)" d="M53 106C82.2711 106 106 82.2711 106 53C106 23.7289 82.2711 0 53 0C23.7289 0 0 23.7289 0 53C0 82.2711 23.7289 106 53 106Z" fill="#0C4B78" />
              <g id="lp-wave_layer_3_bubble_6" filter="url(#lp-filter68_d_2445_3762)" transform="translate(0 146)">
                <path d="M97.5 195C151.348 195 195 151.348 195 97.5001C195 43.6523 151.348 0 97.5 0C43.6522 0 0 43.6523 0 97.5001C0 151.348 43.6522 195 97.5 195Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_5" filter="url(#lp-filter69_d_2445_3762)" transform="translate(233 434)">
                <path d="M83 166C128.84 166 166 128.84 166 83.0001C166 37.1604 128.84 0 83 0C37.1604 0 0 37.1604 0 83.0001C0 128.84 37.1604 166 83 166Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_4" filter="url(#lp-filter70_d_2445_3762)" transform="translate(425 464)">
                <path d="M83 166C128.84 166 166 128.84 166 83.0001C166 37.1604 128.84 0 83 0C37.1604 0 0 37.1604 0 83.0001C0 128.84 37.1604 166 83 166Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_3" filter="url(#lp-filter71_d_2445_3762)" transform="translate(359 454)">
                <path d="M83 166C128.84 166 166 128.84 166 83.0001C166 37.1604 128.84 0 83 0C37.1604 0 0 37.1604 0 83.0001C0 128.84 37.1604 166 83 166Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_2" filter="url(#lp-filter72_d_2445_3762)" transform="translate(44 122)">
                <path d="M37.5 75C58.2107 75 75 58.2107 75 37.5C75 16.7893 58.2107 0 37.5 0C16.7893 0 0 16.7893 0 37.5C0 58.2107 16.7893 75 37.5 75Z" fill="#0C4B78" />
              </g>
              <g id="lp-wave_layer_3_bubble_1" filter="url(#lp-filter73_d_2445_3762)" transform="translate(183 424)">
                <path d="M37.5 75C58.2107 75 75 58.2107 75 37.5C75 16.7893 58.2107 0 37.5 0C16.7893 0 0 16.7893 0 37.5C0 58.2107 16.7893 75 37.5 75Z" fill="#0C4B78" />
              </g>
              <g filter="url(#lp-filter74_d_2445_3762)" transform="translate(26.5 172.078)">
                <path d="M0 562.921V80.9207C0 80.9207 63.5 -10.0775 170.5 0.922587C277.5 11.9227 160.641 184.384 213.5 272.923C281.528 386.87 473.46 233.968 545.5 345.423C588.327 411.681 517.5 562.921 517.5 562.921H0Z" fill="#0C4B78" />
              </g>
            </g>
          </g>
          <g className="landing-smoke-layer" style={{ animationDelay: 'calc(var(--enter-start) + 220ms)' }}>
            <g id="lp-wave_layer_2" filter="url(#lp-filter75_d_2445_3762)" transform="translate(146.376 286.886)">
              <path d="M0 612.035V130.035C0 130.035 65 -10.3859 172 0.614258C279 11.6144 74.0707 347.924 333.5 313.114C531 286.614 509.46 325.16 581.5 436.614C624.327 502.872 517.5 612.035 517.5 612.035H0Z" fill="#41B8E1" />
            </g>
          </g>
          <g className="landing-smoke-layer" style={{ animationDelay: 'calc(var(--enter-start) + 330ms)' }}>
            <g id="lp-wave_layer_1" filter="url(#lp-filter76_d_2445_3762)" transform="translate(167.242 491.34)">
              <path d="M16.6341 317.66V158.66C16.6341 158.66 -39.3658 -5.83911 54.1342 0.1604C147.634 6.15991 240.134 181.16 294.134 188.66C324.839 192.925 416.634 167.66 493.134 167.66C572.028 167.66 636.134 317.66 636.134 317.66H16.6341Z" fill="#F97979" />
            </g>
          </g>
        </g>
      </g>
      <defs>
        <filter id="lp-filter49_d_2445_3762" x="-34.5942" y="-38.8816" width="128.83" height="130.061" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter50_d_2445_3762" x="-34.1624" y="-38.3962" width="137.921" height="139.136" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter51_d_2445_3762" x="-33.9927" y="-38.2055" width="166.564" height="167.771" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter52_d_2445_3762" x="-35.3123" y="-39.6887" width="151.342" height="152.598" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter53_d_2445_3762" x="-35.0908" y="-39.4398" width="177.875" height="179.122" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter54_d_2445_3762" x="-33.395" y="-37.5338" width="165.305" height="166.493" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter55_d_2445_3762" x="-35.0758" y="-39.4229" width="203.844" height="205.093" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter56_d_2445_3762" x="-34.8063" y="-39.12" width="200.277" height="201.516" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter57_d_2445_3762" x="-34.6769" y="-38.9746" width="114.17" height="115.405" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter58_d_2445_3762" x="-34.7756" y="-39.0854" width="97.212" height="98.4479" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter59_d_2445_3762" x="-36.1062" y="-40.581" width="591.144" height="450.248" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter60_d_2445_3762" x="-36.1062" y="-40.581" width="947.014" height="870.922" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter61_d_2445_3762" x="-35.1566" y="-39.3233" width="121.014" height="121.902" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter62_d_2445_3762" x="-35.0072" y="-39.1562" width="135.7" height="136.584" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter63_d_2445_3762" x="-34.675" y="-38.7847" width="214" height="214.874" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter64_d_2445_3762" x="-34.4678" y="-38.5529" width="107.564" height="108.434" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter65_d_2445_3762" x="-35.9684" y="-40.2313" width="181.723" height="182.631" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter66_d_2445_3762" x="-35.7235" y="-39.9575" width="181.208" height="182.109" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter67_d_2445_3762" x="-33.8224" y="-37.831" width="220.205" height="221.057" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter68_d_2445_3762" x="-35.3924" y="-39.5871" width="269.511" height="270.405" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter69_d_2445_3762" x="-35.2548" y="-39.4332" width="240.221" height="241.11" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter70_d_2445_3762" x="-35.3751" y="-39.5677" width="240.474" height="241.366" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter71_d_2445_3762" x="-34.9583" y="-39.1016" width="239.596" height="240.479" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter72_d_2445_3762" x="-34.7928" y="-38.9164" width="148.248" height="149.125" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter73_d_2445_3762" x="-36.0923" y="-40.3699" width="150.983" height="151.894" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter74_d_2445_3762" x="-36.8741" y="-41.2444" width="636.889" height="641.482" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.0470588 0 0 0 0 0.294118 0 0 0 0 0.470588 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter75_d_2445_3762" x="-37.5565" y="-41.6313" width="670.696" height="691.335" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.254902 0 0 0 0 0.721569 0 0 0 0 0.882353 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter76_d_2445_3762" x="-37.5299" y="-41.6522" width="715.144" height="396.997" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset dx="2" dy="-2" />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.976471 0 0 0 0 0.47451 0 0 0 0 0.47451 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
      </defs>
    </svg>
  )
}
