// Generated by scripts/split-landing-svg.py from "src/assets/2_Deep_Space 14.svg". Do not edit by hand.
import './Sparkles.css'

/** Sparkle stars, diamonds and dots around the rocket. Full-frame (4075×1545) layer of the Figma landing page. */
export default function Sparkles({
  className,
  preserveAspectRatio,
}: {
  className?: string
  preserveAspectRatio?: string
}) {
  return (
    <svg
      viewBox="0 0 4075 1545"
      preserveAspectRatio={preserveAspectRatio}
      overflow="visible"
      fill="none"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <g transform="translate(-380.509 -105.001)">
        <g transform="translate(446.509 272.001)">
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 55ms)' }}>
            <g id="lp-Vector_1317" filter="url(#lp-filter31_d_2445_3762)" transform="translate(269 120)">
              <path d="M11.5 0L14.03 8.97L23 11.5L14.03 14.03L11.5 23L8.96999 14.03L0 11.5L8.96999 8.97L11.5 0Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 715ms)' }}>
            <g id="lp-Vector_1318" filter="url(#lp-filter32_d_2445_3762)" transform="translate(331 947)">
              <path d="M18.1667 0L22.1634 14.17L36.3333 18.1667L22.1634 22.1633L18.1667 36.3333L14.17 22.1633L0 18.1667L14.17 14.17L18.1667 0Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 220ms)' }}>
            <g id="lp-Vector_1319" opacity="0.828786" filter="url(#lp-filter33_d_2445_3762)" transform="translate(114 7)">
              <path d="M18.1667 0L22.1634 14.17L36.3333 18.1667L22.1634 22.1633L18.1667 36.3333L14.17 22.1633L0 18.1667L14.17 14.17L18.1667 0Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 165ms)' }}>
            <g id="lp-Vector_1320" filter="url(#lp-filter34_d_2445_3762)" transform="translate(0 395)">
              <path d="M18.1667 0L22.1634 14.17L36.3333 18.1667L22.1634 22.1633L18.1667 36.3333L14.17 22.1633L0 18.1667L14.17 14.17L18.1667 0Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 385ms)' }}>
            <g id="lp-Vector_1321" filter="url(#lp-filter35_d_2445_3762)" transform="translate(603.896 204.146)">
              <path d="M11.3542 0L13.8521 8.85624L22.7083 11.3542L13.8521 13.8521L11.3542 22.7083L8.85624 13.8521L0 11.3542L8.85624 8.85624L11.3542 0Z" fill="#A6857A" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 660ms)' }}>
            <g id="lp-Vector_1322" opacity="0.828786" filter="url(#lp-filter36_d_2445_3762)" transform="translate(801.458 388.083)">
              <path d="M13.625 0L16.6225 10.6275L27.25 13.625L16.6225 16.6225L13.625 27.25L10.6275 16.6225L0 13.625L10.6275 10.6275L13.625 0Z" fill="#A6857A" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 495ms)' }}>
            <g id="lp-Vector_1323" filter="url(#lp-filter37_d_2445_3762)" transform="translate(380 683)">
              <path d="M11.3542 0L13.8521 8.85624L22.7083 11.3542L13.8521 13.8521L11.3542 22.7083L8.85624 13.8521L0 11.3542L8.85624 8.85624L11.3542 0Z" fill="#A6857A" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 550ms)' }}>
            <g id="lp-Vector_1324" filter="url(#lp-filter38_d_2445_3762)" transform="translate(721 570)">
              <path d="M9.08333 18.1667C14.0999 18.1667 18.1667 14.0999 18.1667 9.08333C18.1667 4.06675 14.0999 0 9.08333 0C4.06675 0 0 4.06675 0 9.08333C0 14.0999 4.06675 18.1667 9.08333 18.1667Z" fill="#A6857A" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 275ms)' }}>
            <g id="lp-Vector_1325" opacity="0.828786" filter="url(#lp-filter39_d_2445_3762)" transform="translate(396)">
              <path d="M7.94792 15.8958C12.3374 15.8958 15.8958 12.3374 15.8958 7.94792C15.8958 3.5584 12.3374 0 7.94792 0C3.5584 0 0 3.5584 0 7.94792C0 12.3374 3.5584 15.8958 7.94792 15.8958Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 0ms)' }}>
            <g id="lp-Vector_1326" filter="url(#lp-filter40_d_2445_3762)" transform="translate(174 292)">
              <path d="M7.94792 15.8958C12.3374 15.8958 15.8958 12.3374 15.8958 7.94792C15.8958 3.5584 12.3374 0 7.94792 0C3.5584 0 0 3.5584 0 7.94792C0 12.3374 3.5584 15.8958 7.94792 15.8958Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 770ms)' }}>
            <g id="lp-Vector_1327" filter="url(#lp-filter41_d_2445_3762)" transform="translate(770 754)">
              <path d="M9.08333 18.1667C14.0999 18.1667 18.1667 14.0999 18.1667 9.08333C18.1667 4.06675 14.0999 0 9.08333 0C4.06675 0 0 4.06675 0 9.08333C0 14.0999 4.06675 18.1667 9.08333 18.1667Z" fill="#BFA673" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 440ms)' }}>
            <g id="lp-Vector_1328" opacity="0.828786" filter="url(#lp-filter42_d_2445_3762)" transform="translate(535 530)">
              <path d="M7.94792 15.8958C12.3374 15.8958 15.8958 12.3374 15.8958 7.94792C15.8958 3.5584 12.3374 0 7.94792 0C3.5584 0 0 3.5584 0 7.94792C0 12.3374 3.5584 15.8958 7.94792 15.8958Z" fill="#A6857A" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 825ms)' }}>
            <g id="lp-Group_14117" filter="url(#lp-filter43_d_2445_3762)" transform="translate(535 972.269) rotate(-12)">
              <path transform="translate(0.000342196 15.1359)" d="M0 0H34.9583" stroke="#A2D483" strokeWidth="5.94292" strokeLinecap="round" />
              <path transform="translate(8.73991 -0.00151356)" d="M0 0L17.4792 30.2748" stroke="#A2D483" strokeWidth="5.94292" strokeLinecap="round" />
              <path transform="translate(8.73991 -0.00151356)" d="M17.4792 0L0 30.2748" stroke="#A2D483" strokeWidth="5.94292" strokeLinecap="round" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 110ms)' }}>
            <g id="lp-Group_14118" transform="translate(44.8661 159.716) rotate(-12)">
              <g filter="url(#lp-filter44_f_2445_3762)" transform="translate(7.90246 0.000317698) rotate(12)">
                <path d="M19.5426 19.0013L19.5425 19.0013L19.5426 19.0013L19.5426 19.0013Z" fill="#141A29" />
                <path d="M0 23.1552L39.0852 14.8474M6.17389 4.1539L32.9112 33.8487M25.7165 0L13.3687 38.0026" stroke="#FFF3B5" strokeWidth="6.79292" strokeLinecap="round" />
              </g>
              <g transform="translate(7.90134 0.00141566) rotate(12)">
                <path d="M19.5426 19.0013L19.5425 19.0013L19.5426 19.0013L19.5426 19.0013Z" fill="#141A29" />
                <path d="M0 23.1552L39.0852 14.8474M6.17389 4.1539L32.9112 33.8487M25.7165 0L13.3687 38.0026" stroke="#FFF3B5" strokeWidth="6.79292" strokeLinecap="round" />
              </g>
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 330ms)' }}>
            <g id="lp-Group_14141" transform="translate(586.345 372.805)">
              <g filter="url(#lp-filter45_f_2445_3762)" transform="translate(28.9046) rotate(45)">
                <path d="M40.875 0H0V40.875H40.875V0Z" fill="#4A819C" />
              </g>
              <path transform="translate(28.904) rotate(45)" d="M40.875 0H0V40.875H40.875V0Z" fill="#9FF1E7" />
              <path transform="translate(20.3207 20.3193)" d="M8.58375 17.1675C13.3244 17.1675 17.1675 13.3244 17.1675 8.58375C17.1675 3.84307 13.3244 0 8.58375 0C3.84307 0 0 3.84307 0 8.58375C0 13.3244 3.84307 17.1675 8.58375 17.1675Z" fill="#E68FBE" />
            </g>
          </g>
          <g className="landing-pop" style={{ animationDelay: 'calc(var(--enter-start) + 605ms)' }}>
            <g id="lp-Group_14119" transform="translate(537.999 766)">
              <g filter="url(#lp-filter46_f_2445_3762)" transform="translate(15.4393) rotate(18)">
                <path d="M49.9583 0H0V49.9583H49.9583V0Z" fill="#A2D483" />
              </g>
              <path transform="translate(15.4384) rotate(18)" d="M49.9583 0H0V49.9583H49.9583V0Z" fill="#A2D483" />
              <path transform="translate(20.2362 20.2351)" d="M11.2407 22.4813C17.4487 22.4813 22.4813 17.4487 22.4813 11.2407C22.4813 5.03263 17.4487 0 11.2407 0C5.03263 0 0 5.03263 0 11.2407C0 17.4487 5.03263 22.4813 11.2407 22.4813Z" fill="#24B1B1" />
            </g>
          </g>
        </g>
      </g>
      <defs>
        <filter id="lp-filter31_d_2445_3762" x="-36.7287" y="-36.7287" width="96.457" height="96.4558" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter32_d_2445_3762" x="-32.0046" y="-32.0046" width="100.342" height="100.343" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter33_d_2445_3762" x="-35.4401" y="-35.4401" width="107.213" height="107.216" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter34_d_2445_3762" x="-36.7287" y="-36.7287" width="109.79" height="109.789" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter35_d_2445_3762" x="-32.0046" y="-32.0046" width="86.7175" height="86.7165" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter36_d_2445_3762" x="-34.4783" y="-34.4783" width="96.2069" height="96.2069" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter37_d_2445_3762" x="-36.7287" y="-36.7287" width="96.1653" height="96.1641" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter38_d_2445_3762" x="-32.0046" y="-32.0046" width="82.1763" height="82.1742" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter39_d_2445_3762" x="-35.9415" y="-35.9415" width="87.7794" height="87.7805" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter40_d_2445_3762" x="-36.7287" y="-36.7287" width="89.3528" height="89.354" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter41_d_2445_3762" x="-32.0046" y="-32.0046" width="82.1763" height="82.1742" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter42_d_2445_3762" x="-34.9526" y="-34.9526" width="85.8011" height="85.8022" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="15" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 0.952941 0 0 0 0 0.709804 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter43_d_2445_3762" x="-61.2972" y="-63.9666" width="157.552" height="158.208" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
          <feOffset />
          <feGaussianBlur stdDeviation="20" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix type="matrix" values="0 0 0 0 0.635294 0 0 0 0 0.831373 0 0 0 0 0.513726 0 0 0 1 0" />
          <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_2445_3762" />
          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_2445_3762" result="shape" />
        </filter>
        <filter id="lp-filter44_f_2445_3762" x="-54.4509" y="-55.8553" width="147.986" height="149.714" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="20" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter45_f_2445_3762" x="-78.4922" y="-78.4927" width="197.861" height="197.862" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="20" result="effect1_foregroundBlur_2445_3762" />
        </filter>
        <filter id="lp-filter46_f_2445_3762" x="-53.0862" y="-53.0865" width="156.131" height="156.129" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
          <feGaussianBlur stdDeviation="20" result="effect1_foregroundBlur_2445_3762" />
        </filter>
      </defs>
    </svg>
  )
}
