// Generated by scripts/rasterize-week4-layers.mjs. Do not edit by hand.

/** Where each layer's cropped sprite sits in the art's 4075x1545 frame, in frame units. */
export const WEEK4_SPRITES: Record<string, { x: number; y: number; w: number; h: number }> = {
  'grid-1': { x: 0, y: 27, w: 2705, h: 1518 },
  'base-1': { x: 669, y: 516, w: 560, h: 356 },
  'base-2': { x: 724, y: 1112, w: 560, h: 357 },
  'base-3': { x: 1481, y: 1169, w: 560, h: 357 },
  'base-4': { x: 1486, y: 524, w: 560, h: 357 },
  'sign-1': { x: 528, y: 0, w: 1665, h: 1448 },
  'top-1': { x: 652, y: 393, w: 574, h: 354 },
  'top-2': { x: 706, y: 990, w: 574, h: 353 },
  'top-3': { x: 1485, y: 1047, w: 574, h: 353 },
  'top-4': { x: 1490, y: 402, w: 574, h: 353 },
  'object-1': { x: 753, y: 189, w: 1311, h: 1091 },
  'object-2': { x: 432, y: 461, w: 308, h: 581 },
  'object-3': { x: 983, y: 470, w: 153, h: 48 },
  'object-4': { x: 1040, y: 700, w: 417, h: 428 },
}
