// Generated by scripts/split-week4-layers.py from "demoexpo.svg". Do not edit by hand.

/**
 * The layers the demo expo is built from, back to front: the floor, then each booth, then what
 * stands on it. Positions are the piece's bounding box in the art's own 4075x1545 frame -- the
 * scene uses them to stagger the load-in across the room and to give each piece its own float.
 */
export const WEEK4_LAYERS = [
  { name: 'grid-1', tier: 'grid', x: -251, y: -531, width: 3151, height: 2854 },
  { name: 'base-1', tier: 'base', x: 671, y: 518, width: 556, height: 352 },
  { name: 'base-2', tier: 'base', x: 724, y: 1112, width: 559, height: 357 },
  { name: 'base-3', tier: 'base', x: 1481, y: 1169, width: 559, height: 357 },
  { name: 'base-4', tier: 'base', x: 1488, y: 527, width: 556, height: 352 },
  { name: 'sign-1', tier: 'sign', x: 166, y: -36, width: 2026, height: 2036 },
  { name: 'top-1', tier: 'top', x: 655, y: 395, width: 569, height: 349 },
  { name: 'top-2', tier: 'top', x: 709, y: 992, width: 569, height: 349 },
  { name: 'top-3', tier: 'top', x: 1487, y: 1049, width: 569, height: 349 },
  { name: 'top-4', tier: 'top', x: 1492, y: 404, width: 569, height: 349 },
  { name: 'object-1', tier: 'object', x: 361, y: 189, width: 1703, height: 1779 },
  { name: 'object-2', tier: 'object', x: 432, y: 462, width: 307, height: 581 },
  { name: 'object-3', tier: 'object', x: 983, y: 470, width: 152, height: 48 },
  { name: 'object-4', tier: 'object', x: 1033, y: 701, width: 423, height: 427 },
] as const
