// Generated by scripts/trace-delta-water.py from "riverdelta.svg". Do not edit by hand.

/**
 * Lines of surf off the beach in the top left, as curves in the art's own 3985x1594 frame.
 *
 * Each crest is a contour of distance from the shore, so it runs parallel to the beach the way a
 * wave does, following every bend of it. `offshore` is how far out it sits in frame units, and
 * `toLand` is the unit vector pointing from the crest at the shore -- the way it washes.
 *
 * They are ordered furthest-out first, which is the order they break in.
 */
export const WAVE_CRESTS = [
  {
    id: 'crest-1',
    offshore: 186,
    length: 1356,
    toLand: { x: -0.12, y: 0.993 },
    d: 'M1434.0 42.0C1424.8 46.9 1394.1 65.2 1379.1 71.7C1364.1 78.1 1417.8 74.8 1344.0 80.6C1270.1 86.4 1078.0 109.6 936.0 106.4C794.0 103.1 580.0 68.0 492.0 61.1C404.0 54.1 458.0 69.2 408.0 64.6C358.0 60.0 242.3 43.6 192.0 33.3C141.7 23.1 120.3 8.2 106.0 3.1',
  },
  {
    id: 'crest-2',
    offshore: 132,
    length: 1529,
    toLand: { x: -0.093, y: 0.996 },
    d: 'M1496.0 87.3C1488.0 89.2 1469.1 91.3 1448.1 98.8C1427.1 106.3 1454.9 121.7 1369.9 132.2C1284.9 142.6 1084.0 164.3 938.0 161.5C792.0 158.7 584.0 122.4 494.0 115.5C404.0 108.5 450.0 124.6 398.0 119.8C346.0 115.0 237.7 99.0 182.0 86.7C126.3 74.4 94.2 54.5 63.8 46.1C33.5 37.6 10.6 37.7 0.0 36.0',
  },
  {
    id: 'crest-3',
    offshore: 80,
    length: 1588,
    toLand: { x: -0.118, y: 0.993 },
    d: 'M1546.7 118.0C1543.4 120.3 1540.0 127.0 1526.9 132.0C1513.8 136.9 1490.9 139.1 1468.1 147.5C1445.3 155.9 1479.0 171.4 1390.0 182.6C1300.9 193.7 1084.0 217.0 934.0 214.5C784.0 212.0 580.0 174.5 490.0 167.5C400.0 160.6 422.0 174.9 394.0 173.0C366.0 171.1 360.0 162.1 322.0 156.0C284.0 150.0 211.7 146.5 166.0 136.6C120.3 126.6 75.6 104.3 48.0 96.2C20.3 88.1 8.0 89.4 0.0 88.0',
  },
] as const
