-- Intentionally empty. The original expansion-v0 schema migration failed on
-- dev/staging (NOT NULL termId on populated DomainLeadAssignment) and never
-- applied in any shared environment. The non-calendar v0 surface has been
-- rolled back from prisma/schema.prisma; calendar tables now ship in
-- 20260512000000_calendar_v0_schema.
--
-- File preserved (not deleted) to keep migration-check.yml's "no deleted
-- migrations" guarantee. Empty SQL is a no-op for Prisma.
