name: Fly Deploy

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy-api:
    name: Deploy API (${{ github.ref_name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config ./dali-api/fly.${{ github.ref_name }}.toml ./dali-api -a dali-api-${{ github.ref_name }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-web:
    name: Deploy Web (${{ github.ref_name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config ./dali-web/fly.${{ github.ref_name }}.toml ./dali-web -a dali-web-${{ github.ref_name }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
